import type { NextPage } from 'next'
import { useTheme } from 'next-themes'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Header from '../components/Header'

const Home: NextPage = () => {
  const { systemTheme, theme, setTheme } = useTheme()
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
  }, [])

  return (
    <div>
      <Head>
        <title>GitHub User Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex flex-col justify-center h-screen px-6 font-space bg-clr-section-light dark:bg-clr-section-dark">
          <Header
            setTheme={setTheme}
            mounted={mounted}
            theme={theme}
            systemTheme={systemTheme}
          />
          <div>content</div>
        </div>
      </main>
    </div>
  )
}

export default Home
